#!/bin/sh

down() {
brightnessctl s 4%-
brightness=$(echo "$(brightnessctl g)/2.55" | bc)
dunstify -a "BRIGHTNESS" "Decreasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-low.svg -r 2593 -u normal
}

up() {
brightnessctl s 4%+
brightness=$(echo "$(brightnessctl g)/2.55" | bc)
dunstify -a "BRIGHTNESS" "Increasing to $brightness%" -h int:value:"$brightness" -i ~/.config/dunst/assets/ui/brightness-high.svg -r 2593 -u normal
}

case "$1" in
  up) up;;
  down) down;;
esac
